### ISSUE TITLE
Flusks repairs automaticaly before being comleatly destroyed

### ISSUE THREAD

**Issue by MaxLevs** [Gaelmare/WaterFlasks#22] opened 2024-06-24 18:55 UTC
When I use flusk to the point of completely crushing it restoures after next usage.

Minecraft version: 1.20.1
TFC version: 3.2.4
WaterFlasks version: 3.0.2

**Comment by Gaelmare** [comment] 2024-08-24 01:21
Duplicate of #21 
Fix in progress.

**Closed as completed by Gaelmare** 2024-08-24 01:21 UTC
